### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ArtelGG** [dnyferguson/MineableSpawners#11]
**Suggestions:**
* Add support to reload the configuration file via. a command (see next line)
* Compact the commands down into something like this:
  * `/mineablespawners <give|set|reload> [args...]`
* Add support for blowing spawners up with an independent drop chance from mining.
* Add an option to ignore creative mode entirely. (`prevent-creative-actions`?)
  * They are constantly spammed with messages for not using silk touch pickaxes, etc...
* Improve the documentation on commands, permissions, etc...

**Comment by ArtelGG** [comment]
Just ran into an error:
```
29.06 14:32:44 [Server] ERROR Could not pass event BlockPlaceEvent to MineableSpawners v2.0.4
29.06.06 14:32:44 [Server] INFO java.lang.IllegalArgumentException: No enum constant org.bukkit.entity.EntityType.
29.06.06 14:32:44 [Server] INFO at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_212]
29.06.06 14:32:44 [Server] INFO at org.bukkit.entity.EntityType.valueOf(EntityType.java:23) ~[patched_1.14.3.jar:git-Paper-111]
29.06.06 14:32:44 [Server] INFO at com.dnyferguson.mineablespawners.listeners.SpawnerPlaceListener.onSpawnerPlace(SpawnerPlaceListener.java:50) ~[?:?]
29.06.06 14:32:44 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor136.execute(Unknown Source) ~[?:?]
29.06.06 14:32:44 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.3.jar:git-Paper-111]
29.06.06 14:32:44 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.3.jar:git-Paper-111]
29.06.06 14:32:44 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.3.jar:git-Paper-111]
29.06.06 14:32:44 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[patched_1.14.3.jar:git-Paper-111]
29.06.06 14:32:44 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:324) ~[patched_1.14.3.jar:git-Paper-111]
29.06.06 14:32:44 [Server] INFO at net.minecraft.server.v1_14_R1.ItemStack.placeItem(ItemStack.java:231) ~[patched_1.14.3.jar:git-Paper-111]
29.06.06 14:32:44 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:495) ~[patched_1.14.3.jar:git-Paper-111]
29.06.06 14:32:44 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1392) ~[patched_1.14.3.jar:git-Paper-111]
29.06.06 14:32:44 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.14.3.jar:git-Paper-111]
29.06.06 14:32:44 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.14.3.jar:git-Paper-111]
29.06.06 14:32:44 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.3.jar:git-Paper-111]
29.06.06 14:32:44 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.3.jar:git-Paper-111]
29.06.06 14:32:44 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.3.jar:git-Paper-111]
29.06.06 14:32:44 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.3.jar:git-Paper-111]
29.06.06 14:32:44 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.3.jar:git-Paper-111]
29.06.06 14:32:44 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002) ~[patched_1.14.3.jar:git-Paper-111]
29.06.06 14:32:44 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995) ~[patched_1.14.3.jar:git-Paper-111]
29.06.06 14:32:44 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115) ~[patched_1.14.3.jar:git-Paper-111]
29.06.06 14:32:44 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:979) ~[patched_1.14.3.jar:git-Paper-111]
29.06.06 14:32:44 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912) ~[patched_1.14.3.jar:git-Paper-111]
29.06.06 14:32:44 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by ghost** [comment]
Error should be fixed as of latest version. As for the suggestions they will be taken into consideration

**Comment by ghost** [comment]
Your suggestions have been added to the new update that has just been released, thanks
