### ISSUE TITLE
[NBTAPI] Wasn't able to find NMS Support! Some functions may not work!      Then crazyenchantments does not work..

### ISSUE THREAD

**Issue by MasterNiitro** [dnyferguson/MineableSpawners#78]
Hello, i tried to download multiple versions of nbtapi and deluxemenus, this is now day 2 i hate to bother you guys but i can't find a solution.. This is the error.

[18:07:07 WARN]: [NBTAPI] [NBTAPI] Wasn't able to find NMS Support! Some functions may not work!
[18:07:07 ERROR]: Error occurred while enabling CrazyEnchantments v1.8-Dev-Build-v8-RELEASE (Is it up to date?)
me.badbones69.crazyenchantments.multisupport.nbttagapi.NbtApiException: Method not loaded! 'ITEMSTACK_NMSCOPY'
        at me.badbones69.crazyenchantments.multisupport.nbttagapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:142) ~[?:?]
        at me.badbones69.crazyenchantments.multisupport.nbttagapi.NBTItem.getCompound(NBTItem.java:32) ~[?:?]
        at me.badbones69.crazyenchantments.multisupport.nbttagapi.NBTReflectionUtil.setData(NBTReflectionUtil.java:467) ~[?:?]
        at me.badbones69.crazyenchantments.multisupport.nbttagapi.NBTCompound.setString(NBTCompound.java:68) ~[?:?]
        at me.badbones69.crazyenchantments.api.CrazyEnchantments.load(CrazyEnchantments.java:200) ~[?:?]
        at me.badbones69.crazyenchantments.Main.onEnable(Main.java:35) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-780]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-780]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-780]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-780]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-780]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594) ~[patched_1.16.5.jar:git-Paper-780]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-780]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-780]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-780]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[18:07:07 INFO]: [CrazyEnchantments] Disabling CrazyEnchantments v1.8-Dev-Build-v8-RELEASE

**Comment by ghost** [comment]
Hi, the error you posted isn't even for this plugin.
