### ISSUE TITLE
Error thrown when attempting to silktouch spawner in paperspigot 1.18

### ISSUE THREAD

**Issue by shilofax** [dnyferguson/MineableSpawners#84]
[21:48:39 ERROR]: Could not pass event BlockBreakEvent to MineableSpawners v3.1.1
com.dnyferguson.mineablespawners.nbtapi.NbtApiException: Exception while getting an Itemstack's NBTCompound!
        at com.dnyferguson.mineablespawners.nbtapi.NBTReflectionUtil.getItemRootNBTTagCompound(NBTReflectionUtil.java:125) ~[MineableSpawners-3.1.1.jar:?]
        at com.dnyferguson.mineablespawners.nbtapi.NBTItem.getCompound(NBTItem.java:53) ~[MineableSpawners-3.1.1.jar:?]
        at com.dnyferguson.mineablespawners.nbtapi.NBTReflectionUtil.setData(NBTReflectionUtil.java:588) ~[MineableSpawners-3.1.1.jar:?]
        at com.dnyferguson.mineablespawners.nbtapi.NBTCompound.setString(NBTCompound.java:102) ~[MineableSpawners-3.1.1.jar:?]
        at com.dnyferguson.mineablespawners.api.API.getSpawnerFromEntityType(API.java:72) ~[MineableSpawners-3.1.1.jar:?]
        at com.dnyferguson.mineablespawners.listeners.SpawnerMineListener.giveSpawner(SpawnerMineListener.java:185) ~[MineableSpawners-3.1.1.jar:?]
        at com.dnyferguson.mineablespawners.listeners.SpawnerMineListener.onSpawnerMine(SpawnerMineListener.java:181) ~[MineableSpawners-3.1.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor176.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:git-Paper-24]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:400) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:354) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:314) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1678) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:34) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:8) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.jar:git-Paper-24]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.jar:git-Paper-24]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.jar:git-Paper-24]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.jar:git-Paper-24]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.jar:git-Paper-24]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.jar:git-Paper-24]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.jar:git-Paper-24]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-24]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.dnyferguson.mineablespawners.nbtapi.NbtApiException: Method not loaded! 'NMSITEM_GETTAG'
        at com.dnyferguson.mineablespawners.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:160) ~[MineableSpawners-3.1.1.jar:?]
        at com.dnyferguson.mineablespawners.nbtapi.NBTReflectionUtil.getItemRootNBTTagCompound(NBTReflectionUtil.java:122) ~[MineableSpawners-3.1.1.jar:?]
        ... 31 more

**Comment by ghost** [comment]
Hi, please try the new update and let me know if its fixed

**Comment by shilofax** [comment]
> Hi, please try the new update and let me know if its fixed

Hi, appreciate the very quick reply.

This issue appears to be resolved!

**Comment by ghost** [comment]
sweet
