### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by DecemAdUnum** [dnyferguson/MineableSpawners#9]
`[22:20:58] [Server thread/WARN]: org.bukkit.plugin.InvalidPluginException: java.lang.IllegalStateException: zip file closed
[22:20:58] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:138)
[22:20:58] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334)
[22:20:58] [Server thread/WARN]: 	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:356)
[22:20:58] [Server thread/WARN]: 	at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114)
[22:20:58] [Server thread/WARN]: 	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[22:20:58] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
[22:20:58] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[22:20:58] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734)
[22:20:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1783)
[22:20:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1591)
[22:20:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[22:20:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
[22:20:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15)
[22:20:58] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[22:20:58] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[22:20:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108)
[22:20:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018)
[22:20:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[22:20:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
[22:20:58] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837)
[22:20:58] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[22:20:58] [Server thread/WARN]: Caused by: java.lang.IllegalStateException: zip file closed
[22:20:58] [Server thread/WARN]: 	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686)
[22:20:58] [Server thread/WARN]: 	at java.util.zip.ZipFile.getEntry(ZipFile.java:315)
[22:20:58] [Server thread/WARN]: 	at java.util.jar.JarFile.getEntry(JarFile.java:240)
[22:20:58] [Server thread/WARN]: 	at java.util.jar.JarFile.getJarEntry(JarFile.java:223)
[22:20:58] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102)
[22:20:58] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:199)
[22:20:58] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97)
[22:20:58] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[22:20:58] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[22:20:58] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[22:20:58] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[22:20:58] [Server thread/WARN]: 	at java.lang.Class.forName(Class.java:348)
[22:20:58] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64)
[22:20:58] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134)
[22:20:58] [Server thread/WARN]: 	... 20 more`

**Comment by ghost** [comment]
Hi, please try restarting the server instead of loading it via plugman and let me know if it still gives you this error

**Comment by ghost** [comment]
Give the most recent version on spigot a shot and open a new issue if its still a problem
